export const DATA = [
    {
        id: 1,
        firstName: 'Taariq',
        lastName: 'Charles',
        role: 'CEO',
        department: 'Executive',
    },
    {
        id: 2,
        firstName: 'Shuaib',
        lastName: 'Jacobs',
        role: 'Attorney',
        department: 'Legal',
    },
    {
        id: 3,
        firstName: 'Avisha',
        lastName: 'Parker',
        role: 'Indian',
        department: 'Cultural',
    },
    {
        id: 4,
        firstName: 'Ibraheem',
        lastName: 'Parker',
        role: 'Haafith',
        department: 'Islamic',
    },
    {
        id: 5,
        firstName: 'Haajr',
        lastName: 'Charles',
        role: 'Princess',
        department: 'Royal',
    },
    {
        id: 6,
        firstName: 'Ayyub',
        lastName: 'Charles',
        role: 'Head of department',
        department: 'Management',
    },
    {
        id: 7,
        firstName: 'Aziz',
        lastName: 'Charles',
        role: 'COO',
        department: 'Executive',
    },
    {
        id: 8,
        firstName: 'Thaabiet',
        lastName: 'Charles',
        role: 'Mechanical engineer',
        department: 'Engineering',
    },
    {
        id: 9,
        firstName: 'Soudaa',
        lastName: 'Charles',
        role: 'Mom',
        department: 'Cultural',
    },
    {
        id: 10,
        firstName: 'Khaalid',
        lastName: 'El Musalati',
        role: 'Yemen Boy',
        department: 'Islamic',
    },
    {
        id: 11,
        firstName: 'Hakeem',
        lastName: 'Al something',
        role: 'Abha Boy',
        department: 'Islamic',
    },
    {
        id: 12,
        firstName: 'Fuad',
        lastName: "Al Ma'Koool",
        role: 'Imam',
        department: 'Islamic',
    },
    {
        id: 13,
        firstName: 'Abduraghmaan',
        lastName: 'Al marryCousin',
        role: 'Safety Officer',
        department: 'Health and Safety',
    },
    {
        id: 14,
        firstName: 'Nawaaf',
        lastName: 'Al donUnderstan ',
        role: 'Computer scientist',
        department: 'IT',
    },
    {
        id: 15,
        firstName: 'Thaamier',
        lastName: 'Al BayCheese',
        role: 'Manager',
        department: 'Management',
    },
    {
        id: 16,
        firstName: 'Nomava',
        lastName: 'Baleni',
        role: 'Single Mom',
        department: 'Cultural',
    },
    {
        id: 17,
        firstName: 'Atisha ',
        lastName: 'Lakhan',
        role: 'Indian',
        department: 'Cultural',
    },
    {
        id: 18,
        firstName: 'Aphiwe',
        lastName: 'Nkosi',
        role: 'Police officer',
        department: 'Legal',
    },
    {
        id: 19,
        firstName: 'Antony',
        lastName: 'Dos santos',
        role: 'GOAT',
        department: 'Executive',
    },
    {
        id: 20,
        firstName: 'Vinicius',
        lastName: 'Junior',
        role: 'Battery',
        department: 'Engineering',
    },
    {
        id: 21,
        firstName: 'Bruno',
        lastName: 'Fernandsh',
        role: 'CTO',
        department: 'Executive',
    },
    {
        id: 22,
        firstName: 'Joshua',
        lastName: 'Zirkzee',
        role: 'Maestro',
        department: 'Engineering',
    },
    {
        id: 23,
        firstName: 'Harry',
        lastName: 'Maguire',
        role: 'ComeBackKing',
        department: 'Executive',
    },
    {
        id: 24,
        firstName: 'Manuel',
        lastName: 'Ugarte',
        role: 'Analyst',
        department: 'IT',
    }
]

