export const DATA = [
    {
        id: 1234567,
        firstName: 'Taariq',
        lastName: 'Charles',
        role: 'CEO',
        department: 'Executive',
    },
    {
        id: 2345678,
        firstName: 'Shuaib',
        lastName: 'Jacobs',
        role: 'Attorney',
        department: 'Legal',
    },
    {
        id: 3456789,
        firstName: 'Avisha',
        lastName: 'Parker',
        role: 'Indian',
        department: 'Cultural',
    },
    {
        id: 4567890,
        firstName: 'Ibraheem',
        lastName: 'Parker',
        role: 'Haafith',
        department: 'Islamic',
    },
    {
        id: 5678901,
        firstName: 'Haajr',
        lastName: 'Charles',
        role: 'Princess',
        department: 'Royal',
    },
    {
        id: 6789012,
        firstName: 'Ayyub',
        lastName: 'Charles',
        role: 'Head of department',
        department: 'Management',
    },
    {
        id: 7890123,
        firstName: 'Aziz',
        lastName: 'Charles',
        role: 'COO',
        department: 'Executive',
    },
    {
        id: 8901234,
        firstName: 'Thaabiet',
        lastName: 'Charles',
        role: 'Mechanical engineer',
        department: 'Engineering',
    },
    {
        id: 9012345,
        firstName: 'Soudaa',
        lastName: 'Charles',
        role: 'Mom',
        department: 'Cultural',
    },
    {
        id: 1023456,
        firstName: 'Khaalid',
        lastName: 'El Musalati',
        role: 'Yemen Boy',
        department: 'Islamic',
    },
    {
        id: 1123456,
        firstName: 'Hakeem',
        lastName: 'Al something',
        role: 'Abha Boy',
        department: 'Islamic',
    },
    {
        id: 1289056,
        firstName: 'Fuad',
        lastName: "Al Ma'Koool",
        role: 'Imam',
        department: 'Islamic',
    },
    {
        id: 1345678,
        firstName: 'Abduraghmaan',
        lastName: 'Al marryCousin',
        role: 'Safety Officer',
        department: 'Health and Safety',
    },
    {
        id: 1456789,
        firstName: 'Nawaaf',
        lastName: 'Al donUnderstan ',
        role: 'Computer scientist',
        department: 'IT',
    },
    {
        id: 1567890,
        firstName: 'Thaamier',
        lastName: 'Al BayCheese',
        role: 'Manager',
        department: 'Management',
    },
    {
        id: 1678901,
        firstName: 'Nomava',
        lastName: 'Baleni',
        role: 'Single Mom',
        department: 'Cultural',
    },
    {
        id: 1789012,
        firstName: 'Atisha ',
        lastName: 'Lakhan',
        role: 'Indian',
        department: 'Cultural',
    },
    {
        id: 1890123,
        firstName: 'Aphiwe',
        lastName: 'Nkosi',
        role: 'Police officer',
        department: 'Legal',
    },
    {
        id: 1901234,
        firstName: 'Antony',
        lastName: 'Dos santos',
        role: 'GOAT',
        department: 'Executive',
    },
    {
        id: 2012345,
        firstName: 'Vinicius',
        lastName: 'Junior',
        role: 'Battery',
        department: 'Engineering',
    },
    {
        id: 2123456,
        firstName: 'Bruno',
        lastName: 'Fernandsh',
        role: 'CTO',
        department: 'Executive',
    },
    {
        id: 2234567,
        firstName: 'Joshua',
        lastName: 'Zirkzee',
        role: 'Maestro',
        department: 'Engineering',
    },
    {
        id: 2345678,
        firstName: 'Harry',
        lastName: 'Maguire',
        role: 'ComeBackKing',
        department: 'Executive',
    },
    {
        id: 2456789,
        firstName: 'Manuel',
        lastName: 'Ugarte',
        role: 'Analyst',
        department: 'IT',
    }
]

